# Generated by Django 4.2.2 on 2023-06-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_image_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
