# Generated by Django 4.2.2 on 2023-06-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
